### ISSUE TITLE
Download issue

### ISSUE THREAD

**Issue by Doltrix** [ErikKusch/KrigR#88] opened 2024-11-23 18:27 UTC
**Describe the bug**
Hello Mr. Kusch. Once again I am using your brilliant creation. I have seen that this time there has been a big update since download_ERA. It is an amazing job.
Well, being straightforward, to my mind I am correctly using the parameters specified, but I still fail to correctly perform the request for information. I get the error :
Permission denied Authentication Failed 401 operation not allowed.
I have tried with:
API_USER: My e-mail registered.
API_KEY : USER ID shown in CDS.
APU_KEY: Personal Access Token shown in CDS.

# Reproducing the bug
```
    Precip_20_22 <- CDownloadS(
      Variable = "total_precipitation",
      CumulVar = TRUE,
      DataSet = "reanalysis-era5-land",
      DateStart = "2020-01-01 00:00",
      DateStop = "2020-12-31 23:00",
      TZone = "UTC",
      TResolution = "day",
      TStep = 1,
      Extent = ext(c(-78.83, -77.87, -0.73, 0.34)),
      FileName = "Precip_20_22",
      Dir = Dir,
      FileExtension = ".nc",
      API_User = API_User,
      API_Key = API_Key,
    )
```

# Screenshots
![image](https://github.com/user-attachments/assets/94065172-b7b1-4a01-9033-67d6c5552ac6)

# Expected behavior
I would simply like to be able to carry out the download.
# Session Information
```
###### CDS Request & Data Download
[1] "Building request"
[1] "Checking request validity"
[1] "Executing request - Notice that time windows may vary slightly at this step due to timezone conversions. This will be resolved automatically."
[1] "## Staging CDS Requests"
[1] "[1/2] TEMP_total_precipitation_00001 (UTC: 2020-01-01 - 2020-09-06)"
Error: permission deniedAuthentication failed401operation not allowedhttps://cds.climate.copernicus.eu/api/retrieve/v1/processes/reanalysis-era5-land/executef96eaac5-97a1-434c-b05c-81e0e99ef5e4
Además: Aviso:
In Meta.Check(DataSet = DataSet, Type = Type, VariableCheck = QueryVariable,  :
  Cannot validate user-specified end date (DateStop) because specified data set is being updated regularly (Lag = 3 month). User-specification may lead to an error.
  
```
  
Perhaps you can find something to help me,
Thanks!!

**Comment by ErikKusch** [comment] 2024-11-25 06:16
Hiya,

using my credentials with your above download specification, I cannot reproduce your error, I am afraid. The error being a 401, this is an authentication error and I can only think of four options:
1. You have not agreed to the terms of using CDS - I do not think this is it, otherwise I believe you would not be able to make an account in the first place.
2. You have not agreed to the terms of using ERA5-Land - again, unlikely and `KrigR` should throw an error telling you that.
3. You are using credentials for the old CDS. As of version 0.5 of `KrigR`, you need to interface with the new CDS: https://cds.climate.copernicus.eu/. The message displayed in your console when loading R says so too. Please make sure you are using the credentials for this new CDS.
4. There may be some confusion about what to use as API_User and API_Key. Please see [here](https://www.erikkusch.com/courses/krigr/setup/) for an overview.

**Comment by Doltrix** [comment] 2024-11-25 11:05
Gracias por su respuesta.
He identificado el problema.
Tengo todos los parámetros aceptados, pero no he verificado mi correo a tiempo mediante el enlace enviado. Ahora mi correo ha quedado deshabilitado.
Creando una nueva cuenta con otro correo ahora funciona.

**Comment by ErikKusch** [comment] 2024-11-25 13:28
Perfect! Thanks for letting me know. Closing this issue. 

Enjoy `KrigR` and reach out whenever you need help again or run into any bugs.

**Closed by ErikKusch** 2024-11-25 13:28 UTC
Labels: bug
