### ISSUE TITLE
Problem when creating a stack of downloaded files.

### ISSUE THREAD

**Issue by Doltrix** [ErikKusch/KrigR#36] opened 2023-06-20 07:19 UTC
Hi. I am downloading data from era5 land over a period of 20 years, but I have the problem that when the download finishes and the stack is created, there is an overestimation of values. My temperature stack shows values up to 30000 °K. This is my code:

Temp_00_20<-download_ERA(
  Variable = '2m_temperature',
  Type = "reanalysis",
  DataSet = "era5-land",
  DateStart = "2000-01-01",
  DateStop = "2020-12-31",
  TResolution = "month",
  TStep = 1,
  Extent = extent(-78.83, -77.87, -0.73, 0.34),
  FUN = 'mean',
  Buffer = 0.5,
  Dir = ('E:/Mensual/Info satelital/Temperatura'),
  FileName = 'Temp_00_20',
  API_User = '***************',
  API_Key = '*********************',
  TryDown = 10,
  Cores=5,
  verbose = TRUE,
  TimeOut = 36000,)
  
  
Thank you for your help Mr.

**Comment by Doltrix** [comment] 2023-06-20 07:27
Here more info:

plot(Temp_00_20$X2000.06.01)
![Layer from stack](https://github.com/ErikKusch/KrigR/assets/119699310/e8f2e1d2-a0de-43f0-8a46-03e92ff52876)

plot(individual)
![Individual download in the process](https://github.com/ErikKusch/KrigR/assets/119699310/063eaa0c-bdf9-4964-95db-8d510fdec17d)

**Comment by ErikKusch** [comment] 2023-06-20 09:00
Heya,

thanks for alerting me tho this. I have not seen this behaviour before. I am perplexed here because `KrigR` does not do anything to the data other than stacking it with the specification you have made in your code.

Is the `X2000.06.01` layer the only problem layer?

**Comment by ErikKusch** [comment] 2023-06-20 09:25
I have reproduced the problem - thanks for the code. Troubleshooting the root of the issue now.

**Comment by ErikKusch** [comment] 2023-06-20 10:28
Fixed with [this commit](https://github.com/ErikKusch/KrigR/pull/37).

Thanks again for highlighting it. The error came from a recent inclusion of `terra` functionality in response to #17.

Please reinstall `KrigR`.

**Closed by ErikKusch** 2023-06-20 10:28 UTC
